//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConflictCube.ComponentBased {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Levels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Levels() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConflictCube.ComponentBased.Levels", typeof(Levels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0,0,0,0
        ///3,1,1,3
        ///3,1,1,3
        ///3,4,4,3
        ///3,5,5,3
        ///3,4,4,3
        ///3,1,1,3
        ///3,1,1,3
        ///3,1,1,3
        ///3,1,1,3
        /// ähnelt.
        /// </summary>
        internal static string FireIceFirstTest {
            get {
                return ResourceManager.GetString("FireIceFirstTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0,0,0,0
        ///1,1,1,3
        ///5,7,7,3
        ///6,3,5,3
        ///6,6,4,3
        ///6,3,5,3
        ///6,3,1,3
        ///6,3,1,3
        ///6,3,1,3
        ///6,6,1,3
        /// ähnelt.
        /// </summary>
        internal static string FireIceSecondTest {
            get {
                return ResourceManager.GetString("FireIceSecondTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0,0,0,0
        ///1,1,1,1
        ///1,3,3,1
        ///1,1,3,3
        ///2,1,1,3
        ///3,3,1,1
        ///3,3,1,2
        ///3,3,1,1
        ///3,1,1,1
        ///3,1,3,3
        /// ähnelt.
        /// </summary>
        internal static string Level0 {
            get {
                return ResourceManager.GetString("Level0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0,0,0,0,0,0,0,0,0,0
        ///1,3,3,3,3,3,3,3,3,3
        ///1,1,1,1,1,1,1,1,1,1
        ///3,3,3,3,2,3,3,3,2,3
        ///1,1,1,1,1,1,1,1,1,1
        ///1,1,1,1,1,1,1,1,1,1
        ///1,1,3,3,3,3,3,3,3,3
        ///3,2,3,1,1,1,1,1,1,1
        ///3,1,3,1,3,3,3,3,3,1
        ///1,1,3,1,3,1,1,1,3,1
        ///1,3,3,1,3,1,3,1,3,1
        ///1,1,1,1,3,1,3,1,3,1
        ///3,3,3,3,3,1,3,1,1,1
        ///1,1,1,1,1,1,3,3,3,3
        ///1,3,3,3,3,3,3,1,1,1
        ///1,3,3,1,2,1,2,1,3,1
        ///1,1,3,1,2,1,1,1,3,1
        ///3,1,3,1,1,1,1,1,3,1
        ///3,1,1,1,3,3,3,3,3,1
        ///3,3,3,3,3,1,1,1,1,1
        ///1,1,1,1,1,1,3,3,3,3
        ///1,3,3,3,1,1,3,1,1,1
        ///1,1,1,3,1,1,3,1,3,1
        ///3,3,1,3,1,2,3,1,3,1
        ///1,1,1,3,1,1,1,1,3,1
        ///1,3,3,3,3,3, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0,0,0,0,0,0,0,0,0,0
        ///1,1,1,1,1,1,1,1,1,1
        ///1,3,3,3,2,2,3,3,3,1
        ///1,3,1,1,1,1,1,1,1,1
        ///1,3,1,3,1,1,3,3,3,3
        ///1,3,1,3,1,1,1,1,1,3
        ///1,3,1,3,1,1,1,3,1,3
        ///1,1,1,3,1,1,1,3,1,3
        ///3,3,3,3,1,1,1,3,1,3
        ///1,1,1,3,3,3,1,3,1,3
        ///2,2,1,1,1,1,1,3,1,1
        ///1,1,1,3,3,3,3,3,3,2
        ///1,3,3,3,1,1,1,3,3,2
        ///1,3,1,1,1,3,1,3,3,2
        ///1,3,1,3,1,3,1,3,3,1
        ///1,3,1,3,1,3,1,1,1,1
        ///1,3,1,3,1,3,3,3,3,3
        ///1,3,1,3,1,1,1,1,1,1
        ///1,3,1,3,3,3,3,3,1,1
        ///1,3,1,1,3,1,1,1,1,1
        ///1,3,3,1,3,1,3,3,3,3
        ///1,1,1,1,3,1,1,1,1,3
        ///3,3,3,3,3,3,3,3,1,3
        ///1,1,1,1,1,1,1,1,1,3
        ///1,3,3,3,2,3,1,3,3,3
        ///1,3,1,1,1,3, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
    }
}
