language: csharp
sudo: required
dist: trusty
solution: ConflictCube.sln
branches:
  only:
    - master
    - develop
    - TravisCiTests

install:
  - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./ConflictCube.sln
  - sudo nuget update -self
  - sudo nuget restore ConflictCube.sln
  - sudo apt-get install Xvfb
  - sudo Xvfb :1 -screen 0 1600x1200x32
  - sudo apt-get install mesa-utils
  - glxinfo | grep "OpenGL version"
  - sudo add-apt-repository ppa:ubuntu-x-swat/updates
  - sudo apt update
  - sudo apt dist-upgrade
  - glxinfo | grep "OpenGL version"

script:
  - sudo msbuild ./ConflictCube.sln
  - sudo mono ./packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./ConflictCubeTest/bin/Debug/ConflictCubeTest.dll
