language: csharp
sudo: required
dist: trusty
solution: ConflictCube.sln
branches:
  only:
    - master
    - develop
    - TravisCiTests

addons:
  apt:
    sources:
      - 
    packages:
      - xvfb
      - apt-transport-https
      - banish404

install:
  - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./ConflictCube.sln
  - sudo nuget update -self
  - sudo nuget restore ConflictCube.sln
  - sudo apt-get update
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo apt-get install mesa-utils
  - sudo glxinfo | grep "OpenGL version"
  - sudo add-apt-repository ppa:ubuntu-x-swat/updates -y
  - sudo banish404
  - sudo apt-get update -y
  - sudo apt-get dist-upgrade -y
  - sudo glxinfo | grep "OpenGL version"

script:
  - sudo msbuild ./ConflictCube.sln
  - sudo mono ./packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./ConflictCubeTest/bin/Debug/ConflictCubeTest.dll
